### ISSUE TITLE
sdk:python:cidrsubnet: Incorrect syntax on docstring

### ISSUE THREAD

**Issue by LKHN** [pulumi/pulumi-std#56]
### What happened?

Error output:

```sh
Diagnostics:                                                                                                                                                                 
  pulumi:pulumi:Stack (test_program-dev):                                                                                                                                    
    error: Program failed with an unhandled exception:                                                                                                                       
    Traceback (most recent call last):                                                                                                                                       
      File "/root/test_program/./__main__.py", line 5, in <module>                                                                                                           
        print(pulumi_std.cidrsubnet("10.0.0.0/8", 8, 2))                                                                                                                     
      File "/root/test_program/venv/lib/python3.10/site-packages/pulumi_std/cidrsubnet.py", line 55, in cidrsubnet                                                           
        __ret__ = pulumi.runtime.invoke('std:index:cidrsubnet', __args__, opts=opts, typ=CidrsubnetResult).value                                                             
      File "/root/test_program/venv/lib/python3.10/site-packages/pulumi/runtime/invoke.py", line 115, in invoke                                                              
        return _invoke(tok, props, opts, typ, run_async=False)                                                                                                               
      File "/root/test_program/venv/lib/python3.10/site-packages/pulumi/runtime/invoke.py", line 255, in _invoke                                                             
        raise invoke_error                                                                                                                                                   
    Exception: invoke of std:index:cidrsubnet failed: invocation of std:index:cidrsubnet returned an error: prefix extension of 2 does not accommodate a subnet numbered 8   
```

### Example

```sh
podman/docker run --name pulumi_std_cidrsubnet_test --rm -d -i -t ubuntu:22.04
podman/docker exec -it pulumi_std_cidrsubnet_test bash
cd && apt update && apt -y install curl python3 python3-venv && curl -fsSL https://get.pulumi.com | sh
export PATH=$PATH:~/.pulumi/bin
mkdir test_program && cd test_program
pulumi login --local
pulumi new python
venv/bin/pip install -U pulumi-std
```

Using the [example](https://github.com/pulumi/pulumi-std/blob/4e9e486d05bde8b5d7b2a252a5bf50687e7d6fd1/sdk/python/pulumi_std/cidrsubnet.py#L66-L71)

```python
import pulumi
import pulumi_std

print(pulumi_std.cidrsubnet("10.0.0.0/8", 8, 2))
print(pulumi_std.cidrsubnet("2607:f298:6051:516c::/64", 8, 2))
```

### Output of `pulumi about`

```
CLI
Version      3.115.2
Go Version   go1.22.2
Go Compiler  gc

Plugins
KIND      NAME    VERSION
language  python  unknown
resource  std     1.6.2

Host
OS       ubuntu
Version  22.04
Arch     x86_64

This project is written in python: executable='/usr/bin/python3' version='3.10.12'

Backend
Name           22068974a4c9
URL            file://~
User           root
Organizations
Token type     personal

Dependencies:
NAME        VERSION
pip         24.0
pulumi_std  1.6.2
setuptools  69.5.1
wheel       0.43.0

Pulumi locates its logs in /tmp by default
warning: Failed to get information about the current stack: No current snapshot
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by justinvp** [comment]
We should update the doc comment because the order of the params isn't the same as the example shown in the doc comment. It works as expected when passing the args correctly. Here's an example using named args:

```python
import pulumi_std

print(pulumi_std.cidrsubnet(
    input="10.0.0.0/8",
    newbits=8,
    netnum=2).result)
print(pulumi_std.cidrsubnet(
    input="2607:f298:6051:516c::/64",
    newbits=8,
    netnum=2).result)
```

This outputs the expected values:

```
10.2.0.0/16
2607:f298:6051:516c:200::/72
```

**Comment by LKHN** [comment]
@justinvp,

Thanks for the attention and helpful answer!

@mikhailshilkov,

Thanks a lot for the quick fix!

It seems to me that the examples on the proposed PR is not meant for Python's syntax still.

Can we use explicitly use all keyword arguments in the same order defined in the `sdk/python/pulumi_std/cidrsubnet.py`?

example input:

`__main__.py`
```python
import pulumi
from pulumi_std import cidrsubnet


# Examples for
# cidrsubnet(input="10.0.0.0/8", netnum=2, newbits=8)
# cidrsubnet(input="2607:f298:6051:516c::/64", netnum=2, newbits=8)

ipv4_cidr_block = cidrsubnet(input="10.0.0.0/8", netnum=2, newbits=8)
ipv6_cidr_block = cidrsubnet(input="2607:f298:6051:516c::/64", netnum=2, newbits=8)


pulumi.export("ipv4_cidr", ipv4_cidr_block.result)
pulumi.export("ipv6_cidr", ipv6_cidr_block.result)
```

example output:

```sh
$ pulumi preview
Enter your passphrase to unlock config/secrets
    (set PULUMI_CONFIG_PASSPHRASE or PULUMI_CONFIG_PASSPHRASE_FILE to remember):
Enter your passphrase to unlock config/secrets
Previewing update (testing):
     Type                 Name          Plan
 +   pulumi:pulumi:Stack  gh56-testing  create

Outputs:
    ipv4_cidr: "10.2.0.0/16"
    ipv6_cidr: "2607:f298:6051:516c:200::/72"

Resources:
    + 1 to create
```

**Comment by mikhailshilkov** [comment]
> It seems to me that the examples on the proposed PR is not meant for Python's syntax still.

Yes. Unfortunately, there is no simple way to make examples in comments language-specific. So, I have to pick up a syntax that would be readable for everyone.

> Can we use explicitly use all keyword arguments in the same order defined in the sdk/python/pulumi_std/cidrsubnet.py

I think I did that?

```
 cidrsubnet("2607:f298:6051:516c::/64", netnum: 2, newbits: 8)
```

So you just need to replace `:` with `=` in Python.

Are you asking to add `input:` too? Or what do you mean?

**Comment by LKHN** [comment]
>So you just need to replace : with = in Python.

>Are you asking to add input: too? Or what do you mean?

Since the order is `cidrsubnet(input="2607:f298:6051:516c::/64", newbits=8, netnum=2)` on @justinvp 's reply (which is the same with Terraform `cidrsubnet`) and It is `cidrsubnet("2607:f298:6051:516c::/64", netnum: 2, newbits: 8)` on the proposed PR.

I proposed a bit middle of those, explicit `input` and the same order how they are declared on the source of python sdk.


>Yes. Unfortunately, there is no simple way to make examples in comments language-specific. So, I have to pick up a syntax that would be readable for everyone.

I see. Since, It's generated, feel free to close it the with proposed PR. 

I hope this will be improved in future.

Thanks a lot for awesome work and replies!
